const pool=require('../config/db'); const {logActivity}=require('./logService');
const {sanitizeTypeSpecificData,storageValue,expandRemovedTypeSpecificKeys}=require('./incidentTypeFields');
// PNP memorandum-style investigation report fields (Sec. I–VI plus header and
// signatory blocks). Officer-authored sections; the AI never writes these.
const pnpFields=['authority','matters_investigated','discussion','conclusion','recommendation','station_name','station_region','station_address','station_email','station_contact','approving_authority_name','approving_authority_rank','recipient_office'];
// Structured incident report detail fields (10-section spec): incident info,
// complainant, victim, suspect, incident details, property/damage, witness,
// evidence, and police action. Officer-authored; the AI never writes these.
const detailFields=['date_reported','time_reported','barangay','city','province','specific_place','blotter_entry_no','complainant_full_name','complainant_age','complainant_sex','complainant_address','complainant_contact_number','complainant_role','victim_full_name','victim_age','victim_sex','victim_address','victim_contact_number','victim_role','victim_injuries','victim_damage_or_loss','suspect_name','suspect_alias','suspect_age','suspect_sex','suspect_address','suspect_physical_description','suspect_status','what_happened','people_involved','sequence_of_events','actions_of_suspect','actions_of_victim','circumstances_before_incident','circumstances_after_incident','property_involved','property_description','quantity','estimated_value','type_of_damage','estimated_damage_cost','witness_name','witness_age','witness_address','witness_contact_number','witness_statement','evidence_available','evidence_type','evidence_description','evidence_location','cctv_available','cctv_description','attached_documents','responding_officers','initial_response','actions_taken','evidence_collected','persons_interviewed','medical_assistance','arrest_made','referral_or_endorsement','current_case_status','report_date','report_time'];
const pnpValues=(data)=>pnpFields.map((field)=>{const value=data[field];return value===undefined?undefined:String(value??'').trim()||null});
const detailValues=(data)=>detailFields.map((field)=>{const value=data[field];return value===undefined?undefined:String(value??'').trim()||null});
// MySQL DATE columns arrive as a JS Date at local midnight; toISOString()
// would shift them a day back in timezones ahead of UTC. Format in local time.
const formatDateColumn=(value)=>value?new Date(value.getTime()-value.getTimezoneOffset()*60000).toISOString().slice(0,10):'';
const base=`SELECT r.*,o.user_id officer_user_id,o.badge_number,o.first_name,o.last_name,o.rank officer_rank,o.unit police_unit FROM reports r JOIN officers o ON o.id=r.officer_id`;
const personTypes=['victim','complainant','witness','suspect','person_of_interest','other'];
async function listReports(q){const page=Math.max(1,parseInt(q.page)||1),limit=Math.min(100,Math.max(1,parseInt(q.limit)||10)),w=[],v=[];if(q.search){const x=`%${q.search}%`;w.push("(r.report_number LIKE ? OR r.title LIKE ? OR r.incident_type LIKE ? OR r.location LIKE ? OR o.badge_number LIKE ? OR CONCAT_WS(' ',o.first_name,o.last_name) LIKE ?)");v.push(x,x,x,x,x,x)}if(q.status){w.push('r.status=?');v.push(q.status)}if(q.incidentType){w.push("FIND_IN_SET(?, REPLACE(r.incident_type, ' ', ''))");v.push(q.incidentType)}if(q.officerId){w.push('r.officer_id=?');v.push(q.officerId)}if(q.dateFrom){w.push('r.incident_date>=?');v.push(q.dateFrom)}if(q.dateTo){w.push('r.incident_date<=?');v.push(q.dateTo)}const c=w.length?`WHERE ${w.join(' AND ')}`:'';const countBase='FROM reports r JOIN officers o ON o.id=r.officer_id';const [[{total}]]=await pool.execute(`SELECT COUNT(*) total ${countBase} ${c}`,v);const sortSql={oldest:'r.created_at ASC',number:'r.report_number ASC',date:'r.incident_date DESC, r.created_at DESC'}[q.sort]||'r.created_at DESC';const [rows]=await pool.execute(`${base} ${c} ORDER BY ${sortSql} LIMIT ${limit} OFFSET ${(page-1)*limit}`,v);return{rows,pagination:{page,limit,total,totalPages:Math.max(1,Math.ceil(total/limit))}}}
async function getReport(id,db=pool){const [rows]=await db.execute(`${base} WHERE r.id=?`,[id]);if(!rows[0])return null;const [people]=await db.execute('SELECT * FROM report_people WHERE report_id=? ORDER BY id',[id]);const legacy={};for(const p of people){if(['victim','complainant','witness','suspect'].includes(p.person_type))legacy[p.person_type]=`${p.first_name} ${p.last_name}`.trim()}return{...rows[0],incident_date:formatDateColumn(rows[0].incident_date),incident_time:rows[0].incident_time?.slice(0,5)||'',date_reported:formatDateColumn(rows[0].date_reported),time_reported:rows[0].time_reported?.slice(0,5)||'',report_date:formatDateColumn(rows[0].report_date),report_time:rows[0].report_time?.slice(0,5)||'',type_specific_data:rows[0].type_specific_data||null,officer_name:`${rows[0].first_name} ${rows[0].last_name}`,people,...legacy}}
async function getAuthorizedReport(id,actor,db=pool){const [rows]=await db.execute(`${base} WHERE r.id=?${actor.role==='officer'?' AND r.officer_id=?':''}`,[id,...(actor.role==='officer'?[actor.officerId]:[])]);if(!rows[0])return null;return getReport(id,db)}
async function logUnauthorizedReportAccess(id,actor,req){const editing=['PUT','PATCH','DELETE'].includes(req.method);await logActivity({actorUserId:actor.userId,action:editing?'UNAUTHORIZED_EDIT_ATTEMPT':'UNAUTHORIZED_REPORT_ACCESS',targetType:'Report',targetId:String(id),description:editing?'An Officer attempted to modify a report outside their ownership.':'An Officer attempted to access a report outside their ownership.',metadata:{method:req.method},ipAddress:req.ip})}
const peopleFrom=(data)=>Array.isArray(data.people)?data.people:personTypes.filter(t=>data[t]).map(t=>{const parts=String(data[t]).trim().split(/\s+/);return{person_type:t,first_name:parts.shift(),last_name:parts.join(' ')||''}});
async function insertPeople(db,id,people){for(const p of people){const type=p.person_type||p.personType,first=p.first_name||p.firstName,last=p.last_name||p.lastName;if(!personTypes.includes(type))throw Object.assign(new Error('Invalid person type'),{status:400});if(!String(first||'').trim()||!String(last||'').trim())throw Object.assign(new Error('People involved require first and last names.'),{status:400});await db.execute('INSERT INTO report_people(report_id,person_type,first_name,middle_name,last_name,sex,date_of_birth,age,address,contact_number,email,identification_details,statement,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[id,type,first,p.middle_name||p.middleName||null,last,p.sex||null,p.date_of_birth||p.dateOfBirth||null,p.age||null,p.address||null,p.contact_number||p.contactNumber||null,p.email||null,p.identification_details||p.identificationDetails||null,p.statement||null,p.notes||null])}}
async function createReport(rawData,actor){const db=await pool.getConnection();try{await db.beginTransaction();const data=expandRemovedTypeSpecificKeys(rawData);const officerId=actor.officerId;if(!officerId)throw Object.assign(new Error('Authenticated Officer is required'),{status:403});const temporary=`TMP-${process.pid}-${process.hrtime.bigint().toString(36)}`;const detailCreate=detailValues(data).map((value)=>value??null);const pnpCreate=pnpValues(data).map((value)=>value??null);const typeSpecific=storageValue(sanitizeTypeSpecificData(data.type_specific_data,data.incident_type))??null;const [r]=await db.execute(`INSERT INTO reports(report_number,officer_id,title,incident_type,incident_date,incident_time,location,summary,narrative,${detailFields.join(',')},${pnpFields.join(',')},type_specific_data,status) VALUES (?,?,?,?,?,?,?,?,?,${detailFields.map(()=>'?').join(',')},${pnpFields.map(()=>'?').join(',')},?,'Draft')`,[temporary,officerId,data.title||null,data.incident_type||null,data.incident_date||null,data.incident_time||null,data.location||null,data.summary||null,data.narrative||null,...detailCreate,...pnpCreate,typeSpecific]);const number=`BW-${new Date().getFullYear()}-${String(r.insertId).padStart(6,'0')}`;await db.execute('UPDATE reports SET report_number=? WHERE id=?',[number,r.insertId]);await insertPeople(db,r.insertId,peopleFrom(data));await logActivity({actorUserId:actor.userId,action:'REPORT_CREATED',targetType:'Report',targetId:number,description:`Created incident report ${number}.`,metadata:{reportStatus:'Draft'}},db);await db.commit();return getReport(r.insertId)}catch(e){await db.rollback();throw e}finally{db.release()}}
async function updateReport(id,rawData,actor){const db=await pool.getConnection();try{await db.beginTransaction();const data=expandRemovedTypeSpecificKeys(rawData);const old=await getAuthorizedReport(id,actor,db);if(!old){await db.rollback();return null}if(old.status==='Submitted')throw Object.assign(new Error('Submitted reports are read-only.'),{status:409});const detailUpdate=detailFields.map((field)=>[field,data[field]===undefined?(old[field]||null):String(data[field]??'').trim()||null]);const pnpUpdate=pnpFields.map((field)=>[field,data[field]===undefined?old[field]:String(data[field]??'').trim()||null]);const typeSpecificUpdate=storageValue(sanitizeTypeSpecificData(data.type_specific_data,data.incident_type??old.incident_type))??old.type_specific_data??null;await db.execute(`UPDATE reports SET title=?,incident_type=?,incident_date=?,incident_time=?,location=?,summary=?,narrative=?,${detailUpdate.map(([field])=>`${field}=?`).join(',')},${pnpUpdate.map(([field])=>`${field}=?`).join(',')},type_specific_data=? WHERE id=? AND officer_id=?`,[data.title??old.title,data.incident_type??old.incident_type,(data.incident_date??old.incident_date)||null,(data.incident_time??old.incident_time)||null,data.location??old.location,data.summary??old.summary,data.narrative??old.narrative,...detailUpdate.map(([,value])=>value),...pnpUpdate.map(([,value])=>value),typeSpecificUpdate,id,actor.officerId]);if(data.people||personTypes.some(t=>data[t]!==undefined)){await db.execute('DELETE FROM report_people WHERE report_id=?',[id]);await insertPeople(db,id,peopleFrom(data))}await logActivity({actorUserId:actor.userId,action:'REPORT_EDITED',targetType:'Report',targetId:old.report_number,description:`Updated incident report ${old.report_number}.`,metadata:{reportStatus:'Draft'}},db);await logActivity({actorUserId:actor.userId,action:'DRAFT_SAVED',targetType:'Report',targetId:old.report_number,description:`Saved draft incident report ${old.report_number}.`,metadata:{reportStatus:'Draft'}},db);await db.commit();return getReport(id)}catch(e){await db.rollback();throw e}finally{db.release()}}
async function submitReport(id,actor){const db=await pool.getConnection();try{await db.beginTransaction();const old=await getAuthorizedReport(id,actor,db);if(!old){await db.rollback();return null}if(old.status==='Submitted'){await db.rollback();return old}const missing=['incident_type','incident_date','incident_time','location','narrative'].filter(k=>!String(old[k]||'').trim());if(missing.length||old.narrative.trim().length<30)throw Object.assign(new Error(missing.length?`Required fields: ${missing.join(', ')}`:'Narrative must be at least 30 characters.'),{status:400});await db.execute("UPDATE reports SET status='Submitted',submitted_at=CURRENT_TIMESTAMP WHERE id=? AND officer_id=?",[id,actor.officerId]);await logActivity({actorUserId:actor.userId,action:'REPORT_SUBMITTED',targetType:'Report',targetId:old.report_number,description:`Submitted incident report ${old.report_number}.`,metadata:{reportStatus:'Submitted'}},db);await db.commit();return getReport(id)}catch(e){await db.rollback();throw e}finally{db.release()}}
async function printReport(id,actor){const report=await getAuthorizedReport(id,actor);if(!report)return null;await logActivity({actorUserId:actor.userId,action:'REPORT_PRINTED',targetType:'Report',targetId:report.report_number,description:`Printed incident report ${report.report_number}.`,metadata:{reportStatus:report.status}});return report}
async function deleteReport(id,actor){const db=await pool.getConnection();try{await db.beginTransaction();const old=await getAuthorizedReport(id,actor,db);if(!old){await db.rollback();return null}if(old.status!=='Draft')throw Object.assign(new Error('Only draft reports can be deleted.'),{status:409});await db.execute('DELETE FROM report_people WHERE report_id=?',[id]);const [r]=await db.execute('DELETE FROM reports WHERE id=? AND officer_id=? AND status=?',[id,actor.officerId,'Draft']);if(!r.affectedRows)throw Object.assign(new Error('Only draft reports can be deleted.'),{status:409});await logActivity({actorUserId:actor.userId,action:'REPORT_DELETED',targetType:'Report',targetId:old.report_number,description:`Deleted draft incident report ${old.report_number}.`,metadata:{reportStatus:'Draft',incidentType:old.incident_type||null}},db);await db.commit();return { deleted:true, report_number:old.report_number }}catch(e){await db.rollback();throw e}finally{db.release()}}

module.exports={listReports,getReport,getAuthorizedReport,logUnauthorizedReportAccess,createReport,updateReport,submitReport,printReport,deleteReport};