const service=require('../services/reportService');const {success,error}=require('../utils/response');
const valid=id=>/^\d+$/.test(id)&&Number(id)>0;
const actor=req=>({userId:req.user.id,officerId:req.user.officer?.id||null,role:req.user.role});
const fail=(res,e)=>error(res,e.status?e.message:'Unable to process report request.',e.status||500);
exports.list=async(req,res)=>{try{const query=req.user.role==='officer'?{...req.query,officerId:req.user.officer.id}:req.query;const x=await service.listReports(query);return res.json({success:true,data:x.rows,pagination:x.pagination})}catch(e){return fail(res,e)}};
exports.get=async(req,res)=>{if(!valid(req.params.id))return error(res,'Invalid report ID.',400);try{const x=await service.getAuthorizedReport(req.params.id,actor(req));if(!x){if(req.user.role==='officer')await service.logUnauthorizedReportAccess(req.params.id,actor(req),req).catch(()=>{});return error(res,'Report not found.',404)}return success(res,x)}catch(e){return fail(res,e)}};
exports.create=async(req,res)=>{if(req.user.role!=='officer')return error(res,'Only Officers may create reports.',403);try{return success(res,await service.createReport(req.body,actor(req)),'Draft report created',201)}catch(e){return fail(res,e)}};
async function own(req,res){const report=await service.getAuthorizedReport(req.params.id,actor(req));if(!report){await service.logUnauthorizedReportAccess(req.params.id,actor(req),req).catch(()=>{});error(res,'Report not found.',404);return null}return report}
exports.update=async(req,res)=>{if(!valid(req.params.id))return error(res,'Invalid report ID.',400);if(req.user.role!=='officer')return error(res,'Only the reporting Officer may edit a report.',403);try{if(!await own(req,res))return;const x=await service.updateReport(req.params.id,req.body,actor(req));return success(res,x,'Draft report updated')}catch(e){return fail(res,e)}};
exports.submit=async(req,res)=>{if(!valid(req.params.id))return error(res,'Invalid report ID.',400);if(req.user.role!=='officer')return error(res,'Only the reporting Officer may submit a report.',403);try{if(!await own(req,res))return;const x=await service.submitReport(req.params.id,actor(req));return success(res,x,'Report submitted')}catch(e){return fail(res,e)}};
exports.print=async(req,res)=>{if(!valid(req.params.id))return error(res,'Invalid report ID.',400);try{if(!await own(req,res))return;const x=await service.printReport(req.params.id,actor(req));return success(res,x,'Report print recorded')}catch(e){return fail(res,e)}};
exports.remove=async(req,res)=>{if(!valid(req.params.id))return error(res,'Invalid report ID.',400);if(req.user.role!=='officer')return error(res,'Only the reporting Officer may delete a report.',403);try{if(!await own(req,res))return;const x=await service.deleteReport(req.params.id,actor(req));return success(res,x,'Draft report deleted')}catch(e){return fail(res,e)}};