-- BLUEWRITE database foundation — MySQL 8.4.x
CREATE DATABASE IF NOT EXISTS bluewrite_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bluewrite_db;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NULL COMMENT 'One-way bcrypt hash; never store plaintext passwords',
  role ENUM('officer','admin') NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  account_locked BOOLEAN NOT NULL DEFAULT FALSE,
  security_review_required BOOLEAN NOT NULL DEFAULT FALSE,
  failed_login_attempts INT UNSIGNED NOT NULL DEFAULT 0,
  locked_until DATETIME NULL DEFAULT NULL,
  last_login_at DATETIME NULL DEFAULT NULL,
  last_login_ip VARCHAR(45) NULL DEFAULT NULL,
  password_changed_at DATETIME NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_users_username UNIQUE (username),
  INDEX idx_users_role (role),
  INDEX idx_users_locked_until (locked_until),
  INDEX idx_users_account_locked (account_locked),
  INDEX idx_users_security_review (security_review_required)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS login_verification_challenges (
  id CHAR(36) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  code_digest CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  attempts_remaining TINYINT UNSIGNED NOT NULL DEFAULT 5,
  send_count TINYINT UNSIGNED NOT NULL DEFAULT 1,
  last_sent_at DATETIME NOT NULL,
  consumed_at DATETIME NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_login_challenge_user (user_id),
  INDEX idx_login_challenge_expires (expires_at),
  CONSTRAINT fk_login_challenge_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS officers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  badge_number VARCHAR(30) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100) NULL,
  last_name VARCHAR(100) NOT NULL,
  `rank` VARCHAR(100) NULL,
  unit VARCHAR(150) NULL,
  department VARCHAR(150) NULL,
  email VARCHAR(255) NULL,
  phone VARCHAR(50) NULL,
  status ENUM('Active','Disabled') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT uq_officers_user UNIQUE (user_id),
  CONSTRAINT uq_officers_badge_number UNIQUE (badge_number),
  CONSTRAINT uq_officers_email UNIQUE (email),
  INDEX idx_officers_status (status),
  CONSTRAINT fk_officers_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  report_number VARCHAR(30) NOT NULL,
  officer_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NULL,
  incident_type VARCHAR(100) NULL,
  incident_date DATE NULL,
  incident_time TIME NULL,
  date_reported DATE NULL COMMENT 'Sec.1 — date the incident was reported',
  time_reported TIME NULL COMMENT 'Sec.1 — time the incident was reported',
  location VARCHAR(500) NULL,
  barangay VARCHAR(100) NULL COMMENT 'Sec.1 — barangay of the incident location',
  city VARCHAR(100) NULL COMMENT 'Sec.1 — city/municipality of the incident location',
  province VARCHAR(100) NULL COMMENT 'Sec.1 — province of the incident location',
  specific_place VARCHAR(255) NULL COMMENT 'Sec.1 — specific place within the location',
  blotter_entry_no VARCHAR(100) NULL COMMENT 'Sec.1 — police blotter entry number for §I AUTHORITY',
  summary TEXT NULL,
  narrative TEXT NULL,
  complainant_full_name VARCHAR(255) NULL COMMENT 'Sec.2 — complainant full name',
  complainant_age VARCHAR(10) NULL COMMENT 'Sec.2 — complainant age',
  complainant_sex VARCHAR(20) NULL COMMENT 'Sec.2 — complainant sex',
  complainant_address VARCHAR(500) NULL COMMENT 'Sec.2 — complainant address',
  complainant_contact_number VARCHAR(50) NULL COMMENT 'Sec.2 — complainant contact number',
  complainant_role VARCHAR(100) NULL COMMENT 'Sec.2 — complainant role in the incident',
  victim_full_name VARCHAR(255) NULL COMMENT 'Sec.3 — victim full name',
  victim_age VARCHAR(10) NULL COMMENT 'Sec.3 — victim age',
  victim_sex VARCHAR(20) NULL COMMENT 'Sec.3 — victim sex',
  victim_address VARCHAR(500) NULL COMMENT 'Sec.3 — victim address',
  victim_contact_number VARCHAR(50) NULL COMMENT 'Sec.3 — victim contact number',
  victim_role VARCHAR(255) NULL COMMENT 'Sec.3 — victim role/relationship to complainant',
  victim_injuries TEXT NULL COMMENT 'Sec.3 — injuries sustained by the victim',
  victim_damage_or_loss TEXT NULL COMMENT 'Sec.3 — damage or loss suffered by the victim',
  suspect_name VARCHAR(255) NULL COMMENT 'Sec.4 — suspect name',
  suspect_alias VARCHAR(255) NULL COMMENT 'Sec.4 — suspect alias/nickname',
  suspect_age VARCHAR(10) NULL COMMENT 'Sec.4 — suspect age',
  suspect_sex VARCHAR(20) NULL COMMENT 'Sec.4 — suspect sex',
  suspect_address VARCHAR(500) NULL COMMENT 'Sec.4 — suspect address',
  suspect_physical_description TEXT NULL COMMENT 'Sec.4 — suspect physical description',
  suspect_status VARCHAR(100) NULL COMMENT 'Sec.4 — suspect status (at large, arrested, identified, unknown)',
  what_happened TEXT NULL COMMENT 'Sec.5 — what happened',
  people_involved TEXT NULL COMMENT 'Sec.5 — people involved in the incident',
  sequence_of_events TEXT NULL COMMENT 'Sec.5 — chronological sequence of events',
  actions_of_suspect TEXT NULL COMMENT 'Sec.5 — actions of the suspect',
  actions_of_victim TEXT NULL COMMENT 'Sec.5 — actions of the victim',
  circumstances_before_incident TEXT NULL COMMENT 'Sec.5 — circumstances before the incident',
  circumstances_after_incident TEXT NULL COMMENT 'Sec.5 — circumstances after the incident',
  property_involved VARCHAR(255) NULL COMMENT 'Sec.6 — property involved',
  property_description TEXT NULL COMMENT 'Sec.6 — description of the property',
  quantity VARCHAR(100) NULL COMMENT 'Sec.6 — quantity of property involved',
  estimated_value VARCHAR(50) NULL COMMENT 'Sec.6 — estimated value of the property',
  type_of_damage VARCHAR(255) NULL COMMENT 'Sec.6 — type of damage',
  estimated_damage_cost VARCHAR(50) NULL COMMENT 'Sec.6 — estimated cost of damage',
  witness_name VARCHAR(255) NULL COMMENT 'Sec.7 — witness name',
  witness_age VARCHAR(10) NULL COMMENT 'Sec.7 — witness age',
  witness_address VARCHAR(500) NULL COMMENT 'Sec.7 — witness address',
  witness_contact_number VARCHAR(50) NULL COMMENT 'Sec.7 — witness contact number',
  witness_statement TEXT NULL COMMENT 'Sec.7 — witness statement',
  evidence_available VARCHAR(20) NULL COMMENT 'Sec.8 — whether evidence is available (Yes/No)',
  evidence_type VARCHAR(255) NULL COMMENT 'Sec.8 — type of evidence',
  evidence_description TEXT NULL COMMENT 'Sec.8 — description of the evidence',
  evidence_location VARCHAR(500) NULL COMMENT 'Sec.8 — where the evidence is located/held',
  cctv_available VARCHAR(20) NULL COMMENT 'Sec.8 — whether CCTV footage is available (Yes/No)',
  cctv_description TEXT NULL COMMENT 'Sec.8 — description of CCTV coverage/footage',
  attached_documents TEXT NULL COMMENT 'Sec.8 — attached supporting documents',
  responding_officers VARCHAR(500) NULL COMMENT 'Sec.9 — responding officers',
  initial_response TEXT NULL COMMENT 'Sec.9 — initial police response',
  actions_taken TEXT NULL COMMENT 'Sec.9 — actions taken by police',
  evidence_collected TEXT NULL COMMENT 'Sec.9 — evidence collected at the scene',
  persons_interviewed TEXT NULL COMMENT 'Sec.9 — persons interviewed',
  medical_assistance VARCHAR(255) NULL COMMENT 'Sec.9 — medical assistance provided',
  arrest_made VARCHAR(20) NULL COMMENT 'Sec.9 — whether an arrest was made (Yes/No)',
  referral_or_endorsement TEXT NULL COMMENT 'Sec.9 — referral or endorsement made',
  current_case_status VARCHAR(100) NULL COMMENT 'Sec.9 — current case status',
  report_date DATE NULL COMMENT 'Sec.10 — date the report was prepared',
  report_time TIME NULL COMMENT 'Sec.10 — time the report was prepared',
  type_specific_data JSON NULL COMMENT 'Dynamic incident-type fields — key/value pairs for the selected incident type(s), validated against the field registry',
  authority TEXT NULL COMMENT 'PNP Investigation Report Sec. I — authority basis (blotter entries, inherent police functions, SOP)',
  matters_investigated TEXT NULL COMMENT 'PNP Investigation Report Sec. II — matters to be investigated (numbered objectives)',
  discussion TEXT NULL COMMENT 'PNP Investigation Report Sec. IV — discussion / evaluation connecting facts to offense elements',
  conclusion TEXT NULL COMMENT 'PNP Investigation Report Sec. V — conclusion establishing who, what, when, where, how',
  recommendation TEXT NULL COMMENT 'PNP Investigation Report Sec. VI — recommended next action (filing of charges, referral, further investigation)',
  station_name VARCHAR(255) NULL COMMENT 'Header block — PNP station name',
  station_region VARCHAR(255) NULL COMMENT 'Header block — regional office',
  station_address VARCHAR(255) NULL COMMENT 'Header block — city/municipality, province, ZIP code',
  station_email VARCHAR(255) NULL COMMENT 'Header block — station email address',
  station_contact VARCHAR(100) NULL COMMENT 'Header block — station telephone number',
  approving_authority_name VARCHAR(255) NULL COMMENT 'Signatory block — approving officer (Chief of Police / OIC) name',
  approving_authority_rank VARCHAR(100) NULL COMMENT 'Signatory block — approving officer rank',
  recipient_office VARCHAR(255) NULL COMMENT 'Memorandum block — FOR line (recipient office/officer)',
  status ENUM('Draft','Submitted') NOT NULL DEFAULT 'Draft',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  submitted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT uq_reports_report_number UNIQUE (report_number),
  INDEX idx_reports_officer_id (officer_id),
  INDEX idx_reports_status (status),
  INDEX idx_reports_incident_date (incident_date),
  INDEX idx_reports_created_at (created_at),
  CONSTRAINT fk_reports_officer FOREIGN KEY (officer_id) REFERENCES officers(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_reports_submission CHECK ((status = 'Draft' AND submitted_at IS NULL) OR (status = 'Submitted' AND submitted_at IS NOT NULL))
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS report_people (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  report_id BIGINT UNSIGNED NOT NULL,
  person_type ENUM('victim','complainant','witness','suspect','person_of_interest','other') NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100) NULL,
  last_name VARCHAR(100) NOT NULL,
  sex ENUM('male','female','other','unknown') NULL,
  date_of_birth DATE NULL,
  age SMALLINT UNSIGNED NULL,
  address VARCHAR(500) NULL,
  contact_number VARCHAR(50) NULL,
  email VARCHAR(255) NULL,
  identification_details VARCHAR(500) NULL,
  statement TEXT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_report_people_report_id (report_id),
  INDEX idx_report_people_person_type (person_type),
  CONSTRAINT fk_report_people_report FOREIGN KEY (report_id) REFERENCES reports(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT chk_report_people_age CHECK (age IS NULL OR age <= 130)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  actor_user_id BIGINT UNSIGNED NULL,
  action VARCHAR(100) NOT NULL,
  target_type VARCHAR(50) NOT NULL,
  target_id VARCHAR(100) NULL,
  description VARCHAR(1000) NOT NULL,
  metadata JSON NULL,
  ip_address VARCHAR(45) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_activity_logs_actor_user_id (actor_user_id),
  INDEX idx_activity_logs_action (action),
  INDEX idx_activity_logs_target_type (target_type),
  INDEX idx_activity_logs_created_at (created_at),
  CONSTRAINT fk_activity_logs_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB;